// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmny3SJUq1l6HHATRibDzea0KXPSP3654',
    appId: '1:594343980407:web:65a3d032ad3b0d4c2e8572',
    messagingSenderId: '594343980407',
    projectId: 'bmi-cob',
    authDomain: 'bmi-cob.firebaseapp.com',
    storageBucket: 'bmi-cob.appspot.com',
    measurementId: 'G-796602QJD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4_Z07OFVdG9jhFWqsJXlr3NLUqCSyqro',
    appId: '1:594343980407:android:8ceba1878e9ff3fb2e8572',
    messagingSenderId: '594343980407',
    projectId: 'bmi-cob',
    storageBucket: 'bmi-cob.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAB4LRfJY1ZEfucDnphXdoQwJQlGGc7Hk',
    appId: '1:594343980407:ios:0df1448018ee6b672e8572',
    messagingSenderId: '594343980407',
    projectId: 'bmi-cob',
    storageBucket: 'bmi-cob.appspot.com',
    iosBundleId: 'com.example.bmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAB4LRfJY1ZEfucDnphXdoQwJQlGGc7Hk',
    appId: '1:594343980407:ios:905c079659a74e3d2e8572',
    messagingSenderId: '594343980407',
    projectId: 'bmi-cob',
    storageBucket: 'bmi-cob.appspot.com',
    iosBundleId: 'com.example.bmi.RunnerTests',
  );
}
